name:                AdventOfCode-cafce25
version:             1.0.0.0
github:              "cafce25/AdventOfCode"
license:             MIT
author:              "cafce25"
maintainer:          "cafce25@jbirk.de"
copyright:           "2020 Jonathan Birk"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/cafce25/AdventOfCode#readme>

dependencies:
- base >= 4.7 && < 5
- Unique
- split
- sort
- pureMD5

library:
  source-dirs: src
